server:
  session-timeout: 3000
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8090
#    uri-encoding: utf-8
#security:
#  basic:
#    enabled: false
#  ssl:
#    key-store : /home/telit/apache-tomcat-8.5.37/conf/1750993_jcxx.hfsjx.cn.jks
#    key-store-password : PSE6WH80
#    key-store-type : JKS
#    key-alias : alias
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.bootdo.**.domain
#[弃用]配置缓存和session存储方式，默认ehcache,可选redis,[弃用]调整至 spring cache type【shiro.用户，权限，session，spring.cache通用】
#[弃用]cacheType: ehcache
#SFTP
sftpUserName : root
sftpPassword : tlt12346
sftpHost : 10.0.174.12
sftpPort : 22

serverUrl : http://103.14.132.117:8082/
uploadUrl : /
uploadFileUrl : uploadFile/
